LOCATIONS = {
    "whytecliff": {
        "name": "Whytecliff Park",
        "area": "West Vancouver",
        "region": "howe_sound",
        "latitude": 49.3729,
        "longitude": -123.2909,
        "marine_latitude": 49.3750,
        "marine_longitude": -123.2917,
        "current_model": {
            "provider": "salishseacast",
            "dataset_id": "ubcSSfDepthAvgdCurrents1h",
            "grid_dataset_id": "ubcSSn2DMeshMaskV21-08",
            "seed_grid_y": 479,
            "seed_grid_x": 328,
            "search_radius": 4,
        },
        "tide_station_id": "5cebf1de3d0f4a073c4bb94c",
        "tide_station_name": "Point Atkinson",
        "current_reference_station": {
            "id": "5dd30650e0fdc4b9b4be6d24",
            "name": "First Narrows",
        },
    },
    "porteau_cove": {
        "name": "Porteau Cove",
        "area": "Howe Sound",
        "region": "howe_sound",
        "latitude": 49.5580,
        "longitude": -123.2360,
        "marine_latitude": 49.5580,
        "marine_longitude": -123.2360,
        "current_model": {
            "provider": "salishseacast",
            "dataset_id": "ubcSSfDepthAvgdCurrents1h",
            "grid_dataset_id": "ubcSSn2DMeshMaskV21-08",
            "seed_grid_y": 511,
            "seed_grid_x": 359,
            "search_radius": 0,
        },
        "tide_station_id": "5cebf1de3d0f4a073c4bb94c",
        "tide_station_name": "Point Atkinson",
    },
    "kelvin_grove": {
        "name": "Kelvin Grove",
        "area": "Lions Bay",
        "region": "howe_sound",
        "latitude": 49.4500,
        "longitude": -123.2400,
        "marine_latitude": 49.4500,
        "marine_longitude": -123.2400,
        "current_model": {
            "provider": "salishseacast",
            "dataset_id": "ubcSSfDepthAvgdCurrents1h",
            "grid_dataset_id": "ubcSSn2DMeshMaskV21-08",
            "seed_grid_y": 491,
            "seed_grid_x": 345,
            "search_radius": 0,
        },
        "tide_station_id": "5cebf1de3d0f4a073c4bb94c",
        "tide_station_name": "Point Atkinson",
    },
    "ogden_point": {
        "name": "Ogden Point",
        "area": "Victoria",
        "region": "south_vancouver_island",
        "latitude": 48.4140,
        "longitude": -123.3910,
        "marine_latitude": 48.4140,
        "marine_longitude": -123.3910,
        "current_model": {
            "provider": "salishseacast",
            "dataset_id": "ubcSSfDepthAvgdCurrents1h",
            "grid_dataset_id": "ubcSSn2DMeshMaskV21-08",
            "seed_grid_y": 300,
            "seed_grid_x": 193,
            "search_radius": 0,
        },
        "tide_station_id": "5cebf1df3d0f4a073c4bbd1e",
        "tide_station_name": "Victoria Harbour",
    },
    "willis_point": {
        "name": "Willis Point",
        "area": "Saanich Inlet",
        "region": "south_vancouver_island",
        "latitude": 48.5750,
        "longitude": -123.4820,
        "marine_latitude": 48.5750,
        "marine_longitude": -123.4820,
        "current_model": {
            "provider": "salishseacast",
            "dataset_id": "ubcSSfDepthAvgdCurrents1h",
            "grid_dataset_id": "ubcSSn2DMeshMaskV21-08",
            "seed_grid_y": 338,
            "seed_grid_x": 201,
            "search_radius": 0,
        },
        "tide_station_id": "5cebf1df3d0f4a073c4bbd2d",
        "tide_station_name": "Patricia Bay",
    },
    "madrona_point": {
        "name": "Madrona Point",
        "area": "Nanoose Bay",
        "region": "central_vancouver_island",
        "latitude": 49.3090,
        "longitude": -124.1540,
        "marine_latitude": 49.3090,
        "marine_longitude": -124.1540,
        "current_model": {
            "provider": "salishseacast",
            "dataset_id": "ubcSSfDepthAvgdCurrents1h",
            "grid_dataset_id": "ubcSSn2DMeshMaskV21-08",
            "seed_grid_y": 528,
            "seed_grid_x": 193,
            "search_radius": 4,
        },
        "tide_station_id": "5cebf1de3d0f4a073c4bb96d",
        "tide_station_name": "Nanaimo Harbour",
    },
}

DEFAULT_LOCATION_ID = "whytecliff"
